### User Registration
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "username": "asdasda",
  "email": "sdds@gmail.com",
  "password": "Lilian4ik123123"
}

### User Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "ROCKEZ666",
  "password": "Lilian4ik123123"
}

> {%
    if (response && response.body) {
        const jwtToken = response.body;
        client.global.set("jwtToken", jwtToken);
        console.log("JWT Token successfully set:", jwtToken);
    } else {
        console.error("Response body is undefined or empty.");
    }
%}

### Create Transaction
POST http://localhost:8080/transactions/createTransaction
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "transactionType": "buy",
  "cryptocurrency": "Bitcoin",
  "price": 6,
  "quantity": 255
}

### Get Current User dto
GET http://localhost:8080/users/currentUserDto
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


### Hello Admin
GET localhost:8080/adminPanel/hello
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


### Hello User
GET localhost:8080/users/helloUser
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Forgot Password
POST http://localhost:8080/auth/sendLinkToResetPassword
Content-Type: application/json

{
  "email": "ghertalilian2006@gmail.com"
}

