### User Registration
POST http://localhost:8080/users/registration
Content-Type: application/json

{
  "username": "test",
  "email": "ghertalilian2006@gmail.com",
  "password": "testpassword"
}

### User Login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "test",
  "password": "testpassword"
}

> {%
    if (response && response.body) {
        const responseBody = response.body;
        client.global.set("jwtToken", responseBody["jwt-token"]);
    } else {
        console.error("Response body is undefined or empty.");
    }
%}

### Create Transaction
POST http://localhost:8080/transactions/createTransaction
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "transactionType": "buy",
  "cryptocurrency": "Bitcoin",
  "price": 40000.50,
  "quantity": 0.5
}


### Hello Admin
GET localhost:8080/adminPanel/hello
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


### Hello User
GET localhost:8080/users/helloUser
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

